<a href="https://colab.research.google.com/github/TranHuyBao0101/THToancaocap/blob/main/BAITAPCHUONG5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TH 1:

In [ ]:
x = 3
print(x)

3


In [5]:
import math
x = 4
x = math.sqrt(1+x)
print(x)

2.23606797749979


In [6]:
import math
x = 6
x = math.sqrt(1+x)
print(x)

2.6457513110645907


TH 2:

In [7]:
import math
x = 3 
lap = 1 
while(x!=math.sqrt(x+1)):
  x = math.sqrt(x+1)
  lap = lap+1
x

1.618033988749895

In [8]:
lap

32

TH 3:


In [11]:
import sympy as sp
from sympy import Symbol
X = Symbol('x')
sp.solve(x-sp.sqrt(1+x),x)


[]

TH 4:

In [12]:
import numpy as np
v1 = np.array([1.,2.,3.])
v2 = np.array([2.,1.,0.])
v3 = v1+v2
v3

array([3., 3., 3.])

In [13]:
3*v1+2*v2

array([7., 8., 9.])

In [14]:
[1,2,3]+[2,1,0]

[1, 2, 3, 2, 1, 0]

In [15]:
3*[1,2,3]+2*[2,1,0]

[1, 2, 3, 1, 2, 3, 1, 2, 3, 2, 1, 0, 2, 1, 0]

In [19]:
v4 = np.hstack([v1,v2])
v4

array([1., 2., 3., 2., 1., 0.])

In [20]:
np.dot(v1,v2)

4.0

In [21]:
angles = np.linspace(0,np.pi/2,5)
angles

array([0.        , 0.39269908, 0.78539816, 1.17809725, 1.57079633])

In [22]:
np.sin(angles)

array([0.        , 0.38268343, 0.70710678, 0.92387953, 1.        ])

In [ ]:
import sympy as np
np.sin(angles)