<a href="https://colab.research.google.com/github/TranHuyBao0101/THToancaocap/blob/main/BAITAPCHUONG5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TH 1:

In [ ]:
x = 3
print(x)

3


In [ ]:
import math
x = 4
x = math.sqrt(1+x)
print(x)

2.23606797749979


In [ ]:
import math
x = 6
x = math.sqrt(1+x)
print(x)

2.6457513110645907


TH 2:

In [ ]:
import math
x = 3 
lap = 1 
while(x!=math.sqrt(x+1)):
  x = math.sqrt(x+1)
  lap = lap+1
x

1.618033988749895

In [ ]:
lap

32

TH 3:


In [ ]:
import sympy as sp
from sympy import Symbol
X = Symbol('x')
sp.solve(x-sp.sqrt(1+x),x)


[]

TH 4:

In [ ]:
import numpy as np
v1 = np.array([1.,2.,3.])
v2 = np.array([2.,1.,0.])
v3 = v1+v2
v3

array([3., 3., 3.])

In [ ]:
3*v1+2*v2

array([7., 8., 9.])

In [ ]:
[1,2,3]+[2,1,0]

[1, 2, 3, 2, 1, 0]

In [ ]:
3*[1,2,3]+2*[2,1,0]

[1, 2, 3, 1, 2, 3, 1, 2, 3, 2, 1, 0, 2, 1, 0]

In [ ]:
v4 = np.hstack([v1,v2])
v4

array([1., 2., 3., 2., 1., 0.])

In [ ]:
np.dot(v1,v2)

4.0

In [ ]:
angles = np.linspace(0,np.pi/2,5)
angles

array([0.        , 0.39269908, 0.78539816, 1.17809725, 1.57079633])

In [ ]:
np.sin(angles)

array([0.        , 0.38268343, 0.70710678, 0.92387953, 1.        ])

In [ ]:
import sympy as np
np.sin(angles)

TH 5:

In [1]:
import numpy as np 
goc = np.pi/3
A = np.array([[np.cos(goc),-np.sin(goc)],[np.sin(goc), np.cos(goc)]])
V = np.array([1. , 0.])
Y = np.dot(A, V)
Y

array([0.5      , 0.8660254])

TH6:

In [2]:
from numpy import diff
dx = 0.1
y = [1,2,3,4,5,6]
dy = diff(y)/dx
dy

array([10., 10., 10., 10., 10.])

In [3]:
z = np.array([1,2,3,4,5,6])
dz = diff(z)/dx
dz

array([10., 10., 10., 10., 10.])

In [4]:
 from numpy import diff
 x = [.1,.2,.5,.6,.7,.8,.9]
 y = [1,2,3,4,4,5,6]
 dydx = diff(y)/diff(x)
 print (dydx)

[10.          3.33333333 10.          0.         10.         10.        ]


Th7 :

In [6]:
from sympy.geometry import *
P1 = Point(0, 0)
P2 = Point(3,4)
P3 = Point(2, -1)
P4 = Point(-1, 5)

In [8]:
# Tạo 2 đoạn dường S1 và S2
S1 = Segment(P1, P2)
S2 = Segment(P3, P4)
# kiểm 3 điểm thẳng hàng 
Point.is_collinear(P1,P2,P3)

False

In [9]:
# độ dài đoạn dường S1
S1.length

5

In [10]:
# lấy trung điểm của đoạn 2 
S2.midpoint

Point2D(1/2, 2)

In [11]:
# tính độ dốc của đường S1
S1.slope

4/3

In [12]:
# Tìm vị trí giao nhau giữa hai đoạn đường 
S1.intersection

<bound method LinearEntity.intersection of Segment2D(Point2D(0, 0), Point2D(3, 4))>

In [14]:
# Góc giữa hai đoạn đường
Segment.angle_between(S1, S2)

acos(sqrt(5)/5)

In [15]:
# Kiểm đoạn đường S1 có chứa điểm S3 hay không ?
S1.contains(P3)

False

In [18]:
# Lập và xem phương trình đường thẳng L1 đi qua 2 điểm P1 và P2:
L1 = Line(P1, P2)
L1.equation()

-4*x + 3*y

In [19]:
# Kiểm tính song song :
L1.is_parallel(S1)

True

In [20]:
L1.is_parallel(S2)

False

TH8 :

In [ ]:
import sympy

TH9 :

In [26]:
from sympy import Symbol, solve, Derivative
x = Symbol('x')
f = -x**2+4*x-3
d1 = Derivative(f,x).doit()
cuctri = solve(d1)
cuctri

[2]

In [27]:
A = cuctri[0]
d2 = Derivative(d1,x).doit()
d2.subs({x:A}).evalf()


-2.00000000000000

In [28]:
x_min = 0
x_max = 4
f.subs({x:A}).evalf()

1.00000000000000

In [29]:
f.subs({x:x_min}).evalf()

-3.00000000000000

In [30]:
f.subs({x:x_max}).evalf()

-3.00000000000000